### ISSUE TITLE
[3.x] No ability anymore to pass guzzle options in 3.x

### ISSUE THREAD

**Issue by glamorous** [craigpaul/laravel-postmark#137]
## Detailed description

Add ability back to override guzzle options like bigger timeouts in config/postmark or at other location.

## Context

Sometimes you need bigger timeout or more control about guzzle. That's not possible anymore because of the changes in 3.x

## Possible implementation

check for guzzle config like other implementations in mailmanager already do or like you did before in 2.x

**Comment by craigpaul** [comment]
Hey @glamorous, I'm definitely willing to look into doing this again. If you want to take a stab at a PR feel free, otherwise I'll try and get to it when I have some free time soon.

**Comment by craigpaul** [comment]
This is resolved in `v3.1.0` with https://github.com/craigpaul/laravel-postmark/commit/f7fa0aa150c65d513f58f14a693169d0eb2201e0
